server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: chatapp-backend
  datasource:
    url: jdbc:h2:file:./data/chatdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000 # 24 hours
  upload:
    dir: ./uploads
  oauth:
    github:
      client-id: Ov23liEYagYJBN7s0Nou
      client-secret: 135d669c9093517471566894090b0c8c5219dc17
